.timer on
.mode column
.echo on

--.output week2.log

--Compare with JOIN and CROSS JOIN
SELECT C.NAME FROM COUNTRY C CROSS JOIN CITY;
SELECT C.NAME FROM COUNTRY C JOIN CITY;


--Like optimizer.
SELECT NAME FROM CITY WHERE NAME LIKE 'P%';
SELECT NAME FROM CITY WHERE NAME >= 'P' AND NAME < 'Q';

--Index issue.
SELECT NAME, LATITUDE FROM CITY WHERE LATITUDE BETWEEN 0 AND 78.13;
SELECT NAME, LATITUDE FROM CITY WHERE LATITUDE >= 0 AND LATITUDE <= 78.13;




